site_name: My Wiki
nav:
- 首页: 'index.md'
- python相关:
    - '数组用法': 'python/numpy.md'
    - '图像绘制': 'python/matplotlib_pyplot.md'
    - '其他' : 'python/other.md'
- Linux相关:
    - 'Linux命令行': 'Linux/linux.md'
    - '后台运行': 'Linux/background.md'
    - 'CPU使用相关': 'Linux/cpu_usage.md'
- ROS相关:
    - 'ROS命令集': 'ROS/ros.md'
    - 'rospy': 'ROS/rospy.md'
    - 'ros in C++': 'ROS/rosc.md'
- proto相关:
    - 'proto': 'Proto/proto.md'
    - 'proto for python': 'Proto/protopy.md'
    - 'proto for C++': 'Proto/protoc.md'
- git相关:
    - '一般使用方法总结': 'Git/usual_use.md'
- conda相关:
    - 'conda环境': 'Conda/env.md'
theme:
  name: 'material'
